### ISSUE TITLE
AJAX

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/projekt-tomo#120]
Ko se predmet ureja, postanejo zadeve kar zamudne, ker je vsak klik request, ki na novo naloži stran. Lahko bi uporabljali tehnologijo iz leta 2006, da bi šlo hitreje...

**Comment by matijapretnar** [comment]
Katere stvari so najbolj zamudne? Vem, da so zamudne, samo bi konkreten seznam, če se da. Tako bom laže ocenil, ali sta dovolj že [Django Turbolinks](https://github.com/dgladkov/django-turbolinks) ali [Django PJAX](https://github.com/eventials/django-pjax) in nam ni treba čarati z uporabniškim vmesnikom v JavaScriptu.

**Comment by lokarM** [comment]
Omejil se bom na urejanje predmeta:
- spreminjanje vrstnega reda nalog
- skopirati več nalog iz enega predmeta v drugega

**Comment by matijapretnar** [comment]
Se strinjam, se omejimo za začetek na #130 in #131.
