### ISSUE TITLE
Prikaz predmeta na prvi strani

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/projekt-tomo#121]
Za predmete, na katere sem naročen, vidim na prvi strani zadnje tri sklope. Pri vseh predmetih, ki jih _ne_ učim prvič, je to brez veze, ker vidim tri skrite predmete, ki jih bomo učili ob koncu semestra, ali pa še to ne. Vidim npr. "V pripravi", "1. izpit" in "2. izpit". To je stran vržen prostor. Enostavno se lahko zbriše te sklope, ali pa se naredi oznako "to delamo zdaj" in potem se bodo prikazovali tisti sklopi, ki so označeni kot "aktivni".

**Comment by matijapretnar** [comment]
Tudi učitelj bo videl zadnje tri odprte predmete, torej isto kot študentje.

**Comment by andrejbauer** [comment]
Ja, to je verjetno najbolje.
