### ISSUE TITLE
Učitelj se lahko spremeni v študenta

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/projekt-tomo#125]
Učitelj lahko samega sebe spremeni v učenca in izgubi nadzor nad predmetom. Aljažu je to uspelo narediti na mobitelu, kjer se hover text ne prikaže.

**Comment by matijapretnar** [comment]
Če se ne motim, je to zaprto z 7d66ed8d28d5f3472a652882d49ee3875f64a1b5. Gumb za spremembo v učenca je za trenutnega uporabnika izklopljen.
