### ISSUE TITLE
Čas oddaje

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#142]
Nekaj učiteljev je prosilo, če bi lahko prišli do podatka, kdaj (datum in ura) je bila posamezna rešitev oddana. 

Prostor za ta podatek je po moje lahko tam, kjer se pregledujejo rešitve (pri žarnici)  in ne bi "podrl" samega videza. Doda  se zraven napisa Vaša rešitev ali pa pred pikico, ki označuje pravilnost (seveda če ostali menite, da bi bilo to smiselno narediti) -

**Comment by matijapretnar** [comment]
To je zaključeno z b90170ec052c7f0ec22292e64978356dc4189fe1.
