### ISSUE TITLE
Preverjanje rešitelja

### ISSUE THREAD

**Issue by slosimon** [ul-fmf/projekt-tomo#145]
Token oddaje se lahko zamenja in ne moremo natančno vedeti kdo je v resnici oddal rešitev, saj je **token vezan na uporabnika** in ne na nalogo+uporabnika. Na ta način lahko nekdo z zbirko žetonov odda npr za vse, ki so na izpitu. Ni pa težko najti žetona na dnu .py datoteke in spremeniti vrednosti in ponovno oddati. Na tak način bi lahko študentje sodelovali na izpitu (npr. skupina 4 študentov si zmenja svoje žetone in vsak reši eno nalogo. Nato se z malo korekcij lahko prikrije, da gre v resnici za isto rešitev. In vsi rešijo izpit v rekordnem času).

**Comment by matijapretnar** [comment]
To, da je token vezan samo na uporabnika in ne tudi na nalogo je bila zavestna odločitev, ker si lahko skupina študentov izmenja tokene ne glede na to, na kaj so vezani.

Ampak ko zdaj še enkrat razmišljam o vsem, vidim, da se v tem primeru tokene da izmenjati že pred izpitom, v drugem primeru pa šele med izpitom, kar je zaradi nadzora računalnikov vseeno težje. Bom popravil.

@lokarm, @andrejbauer, @jaanos, @gregorjerse – kakšno je pa vaše mnenje?

**Comment by jaanos** [comment]
Se strinjam, da je bolje, da so tokeni vezani tudi na nalogo.

**Comment by andrejbauer** [comment]
Jaz sem za to, da se ne da goljufati.

**Comment by matijapretnar** [comment]
A se kdo javi za pull request?

**Comment by matijapretnar** [comment]
Sem se jaz, ko imamo jutri ravno izpit. Se priporočam za komentarje.

**Comment by slosimon** [comment]
Če bi se dalo dobiti kakšno dummy nalogo z vezanim token-om in še enega dummy študenta (poleg mojega računa), lahko preverim za python, če je sedaj ok.

**Comment by matijapretnar** [comment]
Zadeva je videti, da dela.
