### ISSUE TITLE
Brisanje starih rešitev

### ISSUE THREAD

**Issue by jaanos** [ul-fmf/projekt-tomo#152]
Letos bomo pri APPR delali več ali manj iste naloge kot lani, kar seveda pomeni, da bom pri prenosu datotek za reševanje že imel vpisane rešitve, ki sem jih napisal lani (in bi jih moral na roko pobrisat pred vajami). Zato bi bilo koristno, da ima (vsaj) učitelj možnost pobrisat vse svoje rešitve pri predmetu, ali vsaj pri sklopu.

**Comment by lokarM** [comment]
Če prav razumem -  ti načeloma misliš uporabljati isti predmet na Tomu ...
Sam osebno sem za to šolsko leto naredil kopije predmetov, ker želim, da imam študente "na novo".  In seveda so potem prenešene le naloge, brez rešitev ... Skratka - počnem isto, kot pri spletni učilnici.

Smo pa se že pogovarjali glede tega, kako celo zadevo organizirati. Tu je še želja (predvsem srednješolskih učiteljev), da bi v sklopu istega predmeta lahko imel študente/dijake razdeljene v skupine ... 

Skratka očitno bi bilo dobro premisliti, kakšen "management" predmetov bi se šli na Tomu ...

**Comment by jaanos** [comment]
To bi tudi šlo, ampak mi bo moral kdo od administratorjev skopirat predmet.

**Comment by matijapretnar** [comment]
Predlagam, da morebitno diskusijo nadaljujemo na #255. Tam sem predlagal, da poskuse briše vsak uporabnik zase (običajno učenci, v tem primeru učitelj). Mogoče kakšen hoče začeti na novo, kdo pa bi rad videl stare rešitve (tega mu učitelj itak ne more preprečiti, ker so rešitve lokalne).
