### ISSUE TITLE
Uvažanje rešitev iz drugih nalog

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#153]
Če imamo dve nalogi, npr. `naloga1.py` in `naloga2.py` in si nekdo v `naloga2.py` želi pomagati s funkcijami iz `naloga1.py`, bi napisal

    from naloga1 import ...

vendar to potem zopet požene teste v `naloga1.py`. Zdi se mi, da se da narediti pogojni stavek, ki teste izvede le, če je datoteka glavna in ne uvožena.

**Comment by lokarM** [comment]
Morda preveč elementarno razmišljam, ampak ali ni tako, da bi potem morali teste vključiti v okolje:
if __name__ == '__main__" :
    # testi, ki se izvedejo le, če je zadeva pognanana kot "samostojna", torej ne z "import"

**Comment by matijapretnar** [comment]
Pri učiteljski verziji, kjer so testi izpostavljeni v kodi, se ti lahko izvedejo, izvesti se ne sme le koda, ki izpiše rezultate in zadevo pošlje na strežnik.
Pri študentski verziji so testi v ločeni funkciji na dnu datoteke, zato lahko izklopimo le to.

**Comment by jakobvalic** [comment]
Sedaj deluje pravilno. Zvijača z `import` in neskončno zanko ne deluje več.
