### ISSUE TITLE
Datoteka za preverjanje uradnih rešitev

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#155]
Testi v učiteljski datoteki se izvajajo med nalogami in v globalnem okolju, tisti v študentski pa v funkciji pod vsemi nalogami ter v lokalnem okolju funkcije. Zato včasih prihaja do razlik, da testi v učiteljski datoteki delajo, testi v študentski pa ne (kakšna spremenljivka ni definirana). Predlagam, da poleg datotek za reševanje in urejanje omogočimo še datoteko za preverjanje uradnih rešitev, ki je videti tako kot tista za reševanje, le da se izpolni z uradnimi rešitvami. Potem se jo samo požene in se vidi, če dela pravilno.

**Comment by lokarM** [comment]
Smiselno

**Comment by KatjaB7** [comment]
Plan dela:
- [ ] Ustvarit datoteko za preverjanje uradnih rešitev
- [ ] Podobno kot na attempt.py datoteki za študente, ne potrbujemo submitov
- [ ] Pregledati kaj obdržati, kaj smiselno nadgraditi
- [ ] Datoteko napolniti z uradnimi rešitvami nalog 
- [ ] Narediti še nov view, gumbe
