### ISSUE TITLE
težave s testom

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#159]
Pri določeni zelo enostavni nalogi 

pri študentu javi 
![image](https://user-images.githubusercontent.com/11019265/32646489-1bdccece-c5ed-11e7-80cc-e6d9de314036.png)

Če isto njegovo rešitev uporabim kot "drug študent" (povsem "navaden" uporabnik), je naloga sprejeta!

Sem prosil za pojasnilo študenta, kakšno sporočilo dobi od Toma (sporočim), a vsekakor je zadeva "čudna". Testna koda za nalogo je:

            try:
               if 'tekmovanje[6]' not in Check.current_part['solution']:
                    Check.error('Napiši ukaz, ki spremeni ustrezno vrednost v tabeli.')
               elif tekmovanje[7] == 150:
                     Check.error('Index prvega elementa je 0.')
               elif tekmovanje[6] != 101 and sum(tekmovanje) == 1210:
                     Check.error('Čas ni prištet pravemu tekmovalcu.')
                elif tekmovanje[6] != 101:
                      Check.error('Rešitev ni prava.')
            except:
                      Check.error('Uporabi tabelo z vrednostimi iz besedila naloge.')

**Comment by lokarM** [comment]
Sem uspel reproducirati napako. Ko je bila rešitev samo za to podnalogo, je bilo vse v redu. Ko pa sem dodal rešitvi druge in tretje podnaloge (kjer tabelo ponovno nastavim na začetne vrednosti), drugih sprememb pa ni, testi javijo, da "Rešitev ni prava."  (torej na indeksu 6 ni več 101). 

Kako je s konteksti rešitev podnalog?

**Comment by matijapretnar** [comment]
Ja, konteksti se pri učitelju in učencu razlikujejo. To je ravno namen #155. Bi bilo pa treba te kontekste razmisliti na novo v sklopu #35.
