### ISSUE TITLE
Lestvice

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#161]
S stališča vzpodbud bi bilo morda smisleno, da bi študenti videli "svojo uvrstitev" - npr. da se jim ob pozsameznem sklopu prikaže še številka, ki bi pomenila, na katerem mestu so glede na število rešenih nalog v tem sklopu. Namreč letos opažam (omenilo pa mi je že več učiteljev), da imam nekaj "tekmovalnih" študentov, ki se načeloma gredo, da bi bili boljši (po številu rešenih nalog) od ostalih ... 

Pa tudi za "zaspanete" bi bilo morda vzpodbuda, da bi videli, da so s svoji številom rešenih nalog šele na 35 mestu med vsem študenti (recimo med 40) .

**Comment by matijapretnar** [comment]
Bom to združil v #129
