### ISSUE TITLE
Skok v novo vrstico pri oddanih in uradnih rešitvah

### ISSUE THREAD

**Issue by martincesnovar** [ul-fmf/projekt-tomo#162]
Če rešitev kopiramo, se vse izpiše v eno vrstico.

**Comment by matijapretnar** [comment]
Če bolj natančno razložim: če gremo na ogled oddane in uradne rešitve, in tam označimo in skopiramo kodo, bo prilepljena koda pristala vsa v eni sami vrstici. Kot sem poskusil, zadeva dela. Zdi se mi, da je bila težava v JavaScriptu, ki je barvala kodo in ob tem namesto golega besedila ustvaril neko kombinacijo divov in spanov, ki se ni lepo prilepila. Zdaj je to verjetno izklopljeno, ker se koda ne barva, zato se rešitve prekopirajo normalno.
