### ISSUE TITLE
Čas oddaje

### ISSUE THREAD

**Issue by martincesnovar** [ul-fmf/projekt-tomo#163]
Se ne posodablja, ko še enkrat oddamo rešitev.

**Comment by schrjako** [comment]
Kolikor jaz stvari vidim bi moralo to biti v redu vsaj od 6da46c68ce90d75950317b37d335fcfb21ea91f2 naprej. Predlagam zaprtje issue-a.

**Comment by matijapretnar** [comment]
Ja, ne vidim razloga, da ga ne bi.
