### ISSUE TITLE
Pozitivna povratna informacija

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#165]
Zanima me, če je možno, da bi napisal teste tudi tako, da bi dal pozitivno povratno informacijo (npr. študentova koda gre čez prvi test (ki je denimo "splošen") - napišemo mu "Čestitam. Tvoja rešitev deluje za tipični problem. Zagotovo si na dobri poti!"

**Comment by matijapretnar** [comment]
Ja, v ta namen obstaja `Check.feedback` - izpisalo se bo tam kakor napake, samo ne bo štelo kot napaka.
