### ISSUE TITLE
Preverjanje rešitev v Octaveu

### ISSUE THREAD

**Issue by jaanos** [ul-fmf/projekt-tomo#169]
@mrcinv, preverjanje rešitev v Octaveu očitno ne deluje pravilno. Za nalogo iz vzorca (s #168, ker mi prej sploh ni hotelo oddajat):
```octave
function p = multiply(x, y)
    p =  x * y
endfunction

check_part();
check_equal('multiply(3, 7)', 21);
check_equal('multiply(6, 7)', 42);
check_equal('multiply(10, 10)', 100);
check_secret(multiply(100, 100));
check_secret(multiply(500, 123));
```
mi sprejme to rešitev:
```octave
function p = multiply(x, y)

endfunction
```
(seveda izpiše kup opozoril, ker nič ne vračam). Tega mi pa seveda ne sprejme:
```octave
function p = multiply(x, y)
  p = x * y + 1
endfunction
```
Izgleda, da bo treba pri primerjavi preverjat še dimenzije odgovorov.

**Comment by mrcinv** [comment]
Sem naredil pull request https://github.com/ul-fmf/projekt-tomo/pull/170
