### ISSUE TITLE
Časovna značka poskusa se ne posodobi

### ISSUE THREAD

**Issue by mrcinv** [ul-fmf/projekt-tomo#189]
Ko oddaš nalogo na strežnik z Matlabom, se časovna značka ne posodobi. Predvidvam, da je to povezano z napako: 

    DATOTEKA Z RE\\u0160ITVIJO IMA ZASTARELO OBLIKO.\\nPROSIMO, PRENESITESI NOVO DATOTEKO S STRANI\\n  http://127.0.0.1:8000/problems/1/download/\"

**Comment by matijapretnar** [comment]
Ja, to je res zaradi tega, rešitev se sploh ne naloži, ampak tu ni pametne rešitve. Trenutno je treba na novo pobrati datoteko, bo pa rešeno, če se bo #156 naredilo tudi za Matlab.
