### ISSUE TITLE
Testi za python uporabljajo nedefinirano spremenljivko s

### ISSUE THREAD

**Issue by TatianaSusnik** [ul-fmf/projekt-tomo#191]
Test `Check.run` uporablja spremenljivko `s`, ki ni definirana. Pojavi se v [datoteki](https://github.com/ul-fmf/projekt-tomo/blob/e0d8474c54bfa5658918e5dbc08094971ac0ae20/web/problems/templates/python/check.py) v vrstici 99. Datoteke, ki za test uporabljajo `Check.run`, ob nepravilno rešeni nalogi vrnejo napako.

**Comment by jaanos** [comment]
Hvala še enkrat za opozorilo, tudi tukaj bi moral biti uporabljen `global_env`. @matijapretnar, spet prosim za deploy.

**Comment by matijapretnar** [comment]
Urejeno.
