### ISSUE TITLE
Polje Course.institution je CharField namesto ForeignKey

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#193]

**Comment by Kriznar4** [comment]
Odličen issue! Načrt je naslednji:
-[ ]
-[ ]
-[ ]
-[ ]
-[ ]
-[ ]

**Comment by Kriznar4** [comment]
Odličen issue! Načrt je naslednji:
- [ ] Naredi model Institution
- [ ] Spremeni Course.institution v ForeignKey
- [ ] Napiši migracijo
- [ ] Popravi tomota tako, da bo vse delovalo
