### ISSUE TITLE
Prikaz v Edge

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#196]
Pikaz v Edge ni OK (CSS?)
![image](https://user-images.githubusercontent.com/11019265/54863200-19f44880-4d46-11e9-9543-8f035029fde7.png)

**Comment by matijapretnar** [comment]
Danes smo poskusili v več brskalnikih Edge in se je v vseh pravilno pokazalo. Verjetno je bila težava v prenosu CSS datoteke.
