### ISSUE TITLE
Pretvorba HTML pomoči v Markdown

### ISSUE THREAD

**Issue by jureslak** [ul-fmf/projekt-tomo#206]
Na https://tomo.fmf.uni-lj.si/help/teachers se izrazi oblike `` `Check.equal()` `` pokazejo dobesedno in ne kot pobarvana koda. Ce namesto tega uporabimo `<code>` tag, je vse ok.

**Comment by matijapretnar** [comment]
To je verjetno zato, ker se Markdown znotraj HTML značk ne pretvarja več (https://daringfireball.net/projects/markdown/syntax#html). Bi bilo pa dobro celotno pomoč pretvoriti iz HTMLja v Markdown. To se da z ustreznim orodjem narediti skoraj avtomatsko.

**Comment by matijapretnar** [comment]
To je verjetno zato, ker se Markdown znotraj HTML značk ne pretvarja več (https://daringfireball.net/projects/markdown/syntax#html). Bi bilo pa dobro celotno pomoč pretvoriti iz HTMLja v Markdown. To se da z ustreznim orodjem narediti skoraj avtomatsko.

**Comment by matijapretnar** [comment]
Sem pridružil v #204.
