### ISSUE TITLE
Progress pri učencih, ki niso reševali nalog iz sklopa

### ISSUE THREAD

**Issue by KraljSamo** [ul-fmf/projekt-tomo#212]
Ko pri posameznem sklopu gledaš seznam učencev in njihovo uspešnost, je to vidno le za učence, ki so to nalogo že uspešno/neuspešno reševali, nimaš pa podatkov o tem, kateri učenci predmeta se teh nalog sploh niso lotili.

Je to namensko narejeno tako? Če ni, se javim, da sam to popravim.

**Comment by matijapretnar** [comment]
V `problems.models` v metodi `Problem.attempts_by_user` je že parameter `active_only=True`, ki določi, a pokaže vse ali samo tiste z rešitvami. Ne spomnim se pa, kako je do tega prišlo. Morda bi bilo dobro to urediti skupaj s skupinami, ki nikoli niso bile urejene do konca. @KraljSamo koliko imaš časa? :)

**Comment by KraljSamo** [comment]
Popravljeno z #219, prikazani so vsi učenci.
