### ISSUE TITLE
UX izboljšave

### ISSUE THREAD

**Issue by jureslak** [ul-fmf/projekt-tomo#221]
Predlagam nekaj (se mi zdi da enostavnih) izboljšav za delo s Tomotom kot učitelj.

Ko imaš seznam sklopov, kot npr. https://www.projekt-tomo.si/course/17/, imaš na desni strani gumbe za premikanje, nstavitve in podobno. Če klikneš na nastavitve in nekaj spremeniš, te potem vrže na sklop sam, kar je zelo tečno, ko hočeš spremeniti 4 sklope zaporedoma, saj moras skakti nazaj.

In obratno, ko gledaš nek sklop, moraš ven iz njega, da lahko spremeniš nastavitve. Tisti del nastavitev, ki se direktno tičejo samo sklopa (torej ne premikanje), bi se lahko ponovil na vrhu sklopa zraven "kapice učitelja", tisti tečni autoredirecti pa bi se lahko umaknili.

Lepo bi bilo med kontrole dodati tudi skrite linke `/tex/`, "`/static/`, `/izpit/` (ceprav ne razumem točno razlike med `static` in `izpit`) in pa link na `/results/`.

Indikator statusa vidljivosti uradnih rešitev, ki ima tudi funkcionalnost, da cikla med različnimi možnostmi, bi se lahko spremenil v read-only in morda pokazal nekje drugje (na zacetku imena s kakšno barvo sorazmerno s permisivnostjo), da nimaš dveh sosdednjih gumbov z možnostjo kako spremeniti stanje uradnih rešitev.

Pod do pregleda predmeta je malo cudna, ker moras uganit, da je treba kliknit na enega izmed krogcev uspeha. To bi bil lahko bolj ekspliciten link.

**Comment by matijapretnar** [comment]
Probably the best solution is to pass around HTTP referrer, so the page that brought you to the edit form. When the form is loaded, this is stored in some hidden attribute and eventually passed into success_url. One possible way is described here: https://stackoverflow.com/questions/68899597/django-how-can-this-updateview-return-to-a-filtered-tableview

**Comment by schrjako** [comment]
Ali zelimo imeti html prikaz tudi za vsako nalogo posamic?

**Comment by matijapretnar** [comment]
Po mojem ni treba
