### ISSUE TITLE
Ni mogoče dodati ustanove (preko admin vmesnika)

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#233]
Ko narediš nov tečaj (Course) ni več možno narediti nove ustanove (z @Ime) ampak lahko izbereš le med obstoječimi. Prosim za hiter popravek ...

![image](https://user-images.githubusercontent.com/11019265/69705846-a1c0fc80-10f6-11ea-9f85-1f1c9aff7ea7.png)

**Comment by matijapretnar** [comment]
Živjo, koda za to je že narejena, samo pravice sem ti pozabil dodeliti :) Zdaj bi moralo delati.
