### ISSUE TITLE
Težave s prijavo

### ISSUE THREAD

**Issue by jaanos** [ul-fmf/projekt-tomo#242]
Na https://www.projekt-tomo.si/ se lahko sicer prijavim preko ArnesAAI s fakultetnim mailom, a me potem prikaže kot **JanoÅ¡ Vidali** in ne vidim svojih predmetov. Je morda šlo kaj narobe na relaciji z ArnesAAI? Do sedaj mi je vedno pravilno pokazalo šumnik v imenu.

**Comment by lokarM** [comment]
Mogoče je kaj v povezavi z malimi/velikimi črkami ... Namreč Admin pokaže:

![Janos](https://user-images.githubusercontent.com/11019265/91703299-3ff85c00-eb7a-11ea-9ea6-e2bba093ca42.png)

**Comment by jaanos** [comment]
Ne, ni razlike pri prijavi z velikimi začetnicami - mogoče pa je prišlo do spremembe pri tem, kako ArnesAAI posreduje e-naslov. Kakorkoli, e-naslovi bi morali biti neobčutljivi na velikost črk.

Mimogrede, po prijavi, ko ArnesAAI vpraša, ali lahko posreduje podatke, se šumnik ustrezno izpiše.

**Comment by matijapretnar** [comment]
Tudi jaz sem imel že enkrat podobno težavo. Bom pogledal ta teden, zdaj ko je konec izpitov.

**Comment by jaanos** [comment]
@matijapretnar, si morda kaj ugotovil?

**Comment by matijapretnar** [comment]
Ok, ko sem pobrisal nov account in na starem dal `username` in `email` (verjetno ta ni ključen) v male črke, je delalo. Očitno potem uspešno najde starega, sicer pa naredi novega. To je seveda ročen popravek, ki ga lahko naredimo po potrebi, ampak issue puščam odprt dokler ne deluje v splošnem.

**Comment by jaanos** [comment]
Mogoče se pa lahko polji za uporabniško ime in e-naslov spremeni na tip [`citext`](https://www.postgresql.org/docs/current/citext.html), da ne bo več prihajalo do takih problemov.

**Comment by matijapretnar** [comment]
Zaenkrat je bil narejen obvod prek 24efd87b82fa3f1ad9887df808a2411a40c64cdf.
