### ISSUE TITLE
Preverjanje uradnih rešitev v obliki, kot jo vidijo študenti

### ISSUE THREAD

**Issue by Petkomat** [ul-fmf/projekt-tomo#254]
Naloga

```
def ali_se_zacne_z_123(x):
    for vrsta in x.split("\n"):
        if not ("1" <= vrsta[0] <= "3"):
            return False
    return True

Check.part()
a = """1
2
3"""
def preveri():
    if not ali_se_zacne_z_123(a):
        Check.error("Ne motiš se ti, motim se jaz!")


preveri()
```

se shrani na strežnik, ampak uradna rešitev hkrati postane napačna (ker se vsebina `a` spremeni). Mogoče so še drugi taki primeri, zato je morda bolj varna pot preverjanja pravilnosti rešitev

1. Tako kot zdaj za začetek.
2. Ustvarjanje datoteke za reševanje, kamor se skopirajo uradne rešitve.
3. Zagon te datoteke.

**Comment by matijapretnar** [comment]
Se strinjam in sem to že parkrat razmišljal. Treba bi bilo dodati še eno vrsto templata, ki je videti kot študentski, samo da nima vključene oddaje, notri se pa dajo uradne rešitve.

**Comment by matijapretnar** [comment]
Ne samo, da sem o tem razmišljal, to je natanko #155 😄
