### ISSUE TITLE
Brisanje starih poskusov

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#255]
Študentje, ki ponavaljajo predmet, si želijo, da se jim stare rešitve pobrišejo. To sem običajno reševal s skripto, ki je brisala stare oddaje, ampak je verjetno bolj enostavno, da ima vsak sklop na vrhu še gumb - pobriši rešitve, pa si lahko vsak pobriše tiste oddaje, ki jih želi.

**Comment by lokarM** [comment]
Če sta dva tipa predmetov - knjižnica nalog in "predmet za vaje" to niti ni tako relevantno - obstajala bo knižnica, kjer so zbrane za predmet primerne naloge, in več predmetov, ki bodo pobrali naloge. Večina nas tako ali tako vsako leto odpre nov predmet (s skopiranimi starimi nalogami) In tu študentov ni (ne novih in ne starih). 

Glede brisanja pa - načeloma si želimo (vsaj nekateri), da zadeve ostanejo - če se bomo želeli iti kako analitiko, prepoznavanje uporsabljenih programskih vzorcev, ...

**Comment by matijapretnar** [comment]
Ja, kot sem že rekel v #69, če poskuse pobrišemo, v zgodovini še vedno ostanejo, tako da za analizo ni težav.

**Comment by matijapretnar** [comment]
Po #30 bo kopiranje predmetov lažje, zato ne bo več potrebe po brisanju poskusov.
