### ISSUE TITLE
Vidnost nalog

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#266]
Že kar nekaj učiteljev (in tudi sam se strinjam z njimi) je predlagalo, da bi bilo možno nastavljati vidnost naloge in ne le celotnega sklopa.  Torej, da bi učitelj imel možnost "učka" ne le pri sklopu, ampak pri posamezni nalogi. 

Ravno danes sem spet dobil e-pošto: 
_"Fino bi bilo, da bi se dalo spremeniti vidnost vsake posamezne naloge in ne le celotnega sklopa. Pripraviš naloge v nekem sklopu vnaprej in jih potem samo "odkrivaš"."_

**Comment by schrjako** [comment]
Tukaj ne vem, kako naj se tomo obnasa v nekaterih primerih. Ko ucitelj prenese _Student files_ ali _Solution files_ ne vem, ali naj bodo v teh datotekah tudi skrite naloge. Ce ja, ali naj bo nekako oznaceno, da so skrite?
Pri _Teacher files_ tudi ne vem, ali naj skrite naloge kako posebej oznacim, ali jih pustim taksne, kot so.
@lokarM ?

**Comment by lokarM** [comment]
Predlagam, da so vključene in označene tudi skrite naloge.

**Comment by schrjako** [comment]
Torej v vseh teh datotekah?
V LaTeX in html predstavi datotek pa ne? To bi se meni zdelo smiselno.

**Comment by matijapretnar** [comment]
Se strinajm. Za učitelja naj bodo naloge vidne:
- na strani sklopa
- v zipu za urejanje
- v zipu z uradnimi rešitvami
- v zipu za reševanje
- v zipu z rezultati
- v statistiki
in skrite
- v HTML izvozu
- v LaTeX izvozu

**Comment by schrjako** [comment]
- [ ] na strani sklopa
- [ ] v zipu za urejanje
- [ ] v zipu z uradnimi rešitvami
- [ ] v zipu za reševanje
- [ ] v zipu z rezultati
- [ ] v statistiki
- [ ] in skrite
- [ ] v HTML izvozu
- [ ] v LaTeX izvozu

**Comment by schrjako** [comment]
Kaj je pomen tega
> in skrite
?

**Comment by matijapretnar** [comment]
To ni del seznama, ampak začetek drugega seznama, kje naj bodo skrite :)

**Comment by schrjako** [comment]
Rad bi dodal se prevode za besedilo, ki sem ga dodal v template-e, vendar mi
> python manage.py makemessages -l sl

ne izpise teh besedil v _web/locale/sl/LC_MESSAGES/django.po_. Ali delam kaj ocitnega narobe?

Primer besedila, ki bi ga prevedel je "This problem is not visible." v _web/problems/templates/python/solution.py_
