### ISSUE TITLE
Možnost popolnega izbrisa iz predmeta

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#69]

**Comment by lokarM** [comment]
Če se nekdo prijavi v določen predmet, rešuje naloge in se potem odjavi od predmeta, ter ponovno projavi, se "stara zgodovina" ohrani. 

Načeloma bi bilo dobro, da se lahko iz predmeta odjaviš tako, da se ti zgodovina zbriše. Tako bo, če se bo k predmetu ponovno prijavil, začel čisto iz nule.

Potrebno pa je premisliti, kaj bomo mi naredili (načeloma bi jaz stare podatke odjavljenih tudi ohranil (za analize) - le označil drugače)

**Comment by matijapretnar** [comment]
V #255 sem predlagal bolj milo varianto, torej da si pri vsakem sklopu lahko resetiraš poskuse. S tem se pobrišejo, v zgodovini za analizo pa še vedno ostanejo.
