### ISSUE TITLE
Prenos ob redirectu

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#72]
Včeraj se nama je z @lokarM zgodilo, da je po urejanju naloge (AJAX forma) in loginu strežnik (Chrome na Windowsih) začel shranjevati datoteko, v kateri je bila zazipana stran, na katero bi moralo preusmeriti. Torej, POST se naredi v redu, potem pa namesto redirecta strežnik vrne stran. V večini poskusov je redirect deloval normalno.

**Comment by lokarM** [comment]
Dajnes se je zadeva ponovila ... (na prenosniku, v Mb)

**Comment by matijapretnar** [comment]
Kot [gledam na Googlu](https://www.google.si/search?client=safari&rls=en&q=chrome+downloads+page+instead+of+opening&ie=UTF-8&oe=UTF-8&gws_rd=cr&ei=HWUZVoiAE-H7ywP4np5Y), zna biti težava s kakšnim pluginom za Chrome. Bojda pomaga, če počistiš cache.

**Comment by matijapretnar** [comment]
@lokarM: A se to še dogaja ali zadevo počasi zapremo?

**Comment by lokarM** [comment]
Ne, meni se stvar ni ponovila nikoli več ...

**Comment by matijapretnar** [comment]
Super!
