### ISSUE TITLE
Označitev pravilnosti podnaloge pri besedilu

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/projekt-tomo#76]
Predlagam, da na strani sklopa pri vsaki podnalogi pobarvamo levi rob odvisno od veljavnosti oddane rešitve. Podatki bi bili sicer isti kot v krogcih na desni, ampak se mi zdi, da je oboje koristno in zato redundanca ni odveč :)

**Comment by sonjajerse** [comment]
Meni se ne zdi potrebno - ravno zaradi tega, ker to informacijo na isti strani že imamo (v obliki krogcev).

**Comment by lokarM** [comment]
Še nekaj redundance načeloma ne škodi, zato sem za Matijevo idejo, še posebej, če gre za zadevo ki mu ne vzame kaj dosti časa ...
