### ISSUE TITLE
Primer predmeta v angleščini

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#90]
Če želimo biti malo odmevni, bi bilo potrebno narediti angleško različico  z vsaj enim predmetom. Mislim, da bi se potem tudi laže "pogajal" z Microsoftom.

**Comment by lokarM** [comment]
Nisem mislil le na en predmet, ampak kompleten svoj sistem (res, da ni veliko slovenščine, ampak je pa)

**Comment by matijapretnar** [comment]
Saj to je načeloma že prevedeno, samo locale v brskalniku je treba nastaviti na angleškega.

**Comment by lokarM** [comment]
No, ob tem je še help in še kaj ... /načeloma pa vsaj pri meni (ali pa ne znam tega narediti) v Windows okolju spreminjanje locale v brskalniku ne pomaga .../

**Comment by katjabercic** [comment]
Obstajata [Demo course](https://www.projekt-tomo.si/problem_set/1997/) za Univerzo v Milanu in [Computer Science](https://www.projekt-tomo.si/course/150/).
