### ISSUE TITLE
Izpis nalog

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#95]
Če ima naloga le eno podnalogo, bi bilo po moje lepše, če bi se besedilo 1. podnaloga spustilo!

**Comment by matijapretnar** [comment]
Ja, se strinjam. Sem imel že sam v mislih.

**Comment by lokarM** [comment]
Ko pregledujemo rešitve študentov, bi morda namesto "Vaša rešitev" pisalo "Rešitev Ime Priimek"
