### ISSUE TITLE
Spletna skupnost

### ISSUE THREAD

**Issue by lokarM** [ul-fmf/projekt-tomo#96]
Morda bi bilo smiselno na strani odpreti kak Forum, kjer bi udeleženci lahko zastavljali vprašanja, ...
Dobro bi imeti dva - za učence in za učitelje, s tem, da učitelj lahko sodeluje (ko je pripravljen z uč. računom) v obeh ...

**Comment by matijapretnar** [comment]
Ideja je dobra, vendar funkcionalnosti foruma nočem dodajati, ker je potem zanjo treba skrbeti in že zdaj je preveč stvari. Lahko pa se forum naredi kje drugje, npr. na Slack/Discourse/…, pa ga smiselno vključimo na stran (lahko kot link, lahko kot embed).

**Comment by lokarM** [comment]
Seveda je bistveno bolj smiselno, da je Forum odprt nekje drugje - v Tomu je samo link ... Tomo naj ostane čim bolj "čist" ...
